spring.application.name=gemma-docker-chat
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
#Gemma Built on top on open ai
spring.ai.openai.chat.options.model=ai/gemma4
#Just the place hold no need to set it up since we are using gemma as the provider
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.base-url=http://localhost:12434/engines