logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
#Gemma Built on top on open ai
spring.ai.openai.chat.options.model=ai/gemma4
#Just the place hold no need to set it up since we are using gemma as the provider
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.base-url=http://localhost:12434/engines
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.datasource.url=jdbc:h2:file:~/chatmemory;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.h2.console.enabled=true